name: Auto-create PR based on comment

on:
  issue_comment:
    types: [created]

jobs:
  get-apps:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && (contains(github.event.comment.body, 'major') || contains(github.event.comment.body, 'minor') || contains(github.event.comment.body, 'patch'))
    outputs:
      apps: ${{ steps.get-labels.outputs.apps }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get PR labels
        id: get-labels
        run: |
          LABELS=$(gh pr view ${{ github.event.issue.number }} --json labels -q '.labels[].name')

          # 임시 JSON 파일 생성
          echo '[]' > apps.json

          while IFS= read -r label; do
            if [[ $label == app:* ]]; then
              APP_NAME=${label#app:}

              # desk -> ch-desk-web 변환
              if [ "$APP_NAME" = "desk" ]; then
                APP_NAME="ch-desk-web"
              fi

              # JSON 배열에 새로운 항목 추가 (따옴표 처리 주의)
              jq --arg name "$APP_NAME" '. += [{"name":$name}]' apps.json > temp.json && mv temp.json apps.json
            fi
          done <<< "$LABELS"

          # 결과 출력 및 이스케이프 처리
          APPS_JSON=$(cat apps.json)
          echo "apps=${APPS_JSON}" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  version-bump:
    needs: get-apps
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ${{ fromJSON(needs.get-apps.outputs.apps) }}
    steps:
      - name: print apps
        run: |
          echo "apps: ${{ needs.get-apps.outputs.apps }}"
